controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_yaw
      - shoulder_pitch
      - elbow
      - wrist_pitch
      - wrist_yaw
      - wrist_roll
  - name: fake_endeffector_controller
    joints:
      - wrist_roll