<?xml version ="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_manipulator">

<material name="orange">
  <color rgba="1 0.487 0 1"/>
</material>  

<material name="white">
  <color rgba="1 1 1 1"/>
</material>  

<material name="green">
  <color rgba="0 0.8 0 1"/>
</material>  



<xacro:property name="MXLength" value="0.0611"/>
<xacro:property name="MXWidth" value="0.041"/>
<xacro:property name="MXDepth" value="0.0402"/>

<xacro:property name="AXLength" value="0.05"/>
<xacro:property name="AXWidth" value="0.032"/>
<xacro:property name="AXDepth" value="0.04"/>

<xacro:property name="length" value="0.096"/>
============================================================================================================================================
<!-- FIXED JOINT MACRO-->
<xacro:macro name="FxdJoint" params="id trans rpy parent child">
    <joint name="${id}" type="fixed">
      <origin xyz="${trans}"  rpy="${rpy}" />
      <parent link="${parent}"/>
      <child link="${child}"/> 
    </joint>
</xacro:macro> 
<!-- REVOLUTE JOINT MACRO-->
<xacro:macro name="Revjoint" params="id trans rpy parent child axis l u v">
    <joint name="${id}" type="revolute">
      <origin xyz="${trans}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${axis}"/>
      <limit lower="${l}" upper="${u}" effort="30" velocity="${v}"/>
    </joint>
</xacro:macro>




<!-- BOT MACRO-->
<xacro:macro name="BotInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="BotVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/bot.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="green"/>         
  </visual>
</xacro:macro>

<xacro:macro name="BotCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/bot.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>
<!-- SHOULDER_YAW MACRO-->
<xacro:macro name="shoulder_yaw_inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="shoulder_yaw_visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/base_motor.STL" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="shoulder_yaw_collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/shoulder_yaw.STL" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>

<!-- SHOULDER_BRAK MACRO-->
<xacro:macro name="shoulder_yaw_brak_inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="shoulder_yaw_brak_visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/shoulder_yaw1.STL" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="shoulder_yaw_brak_collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/shoulder_yaw1.STL" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>

<!-- SHOULDER_PITCH MACRO-->
<xacro:macro name="shoulder_pitch_inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="shoulder_pitch_visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/shoulder_pitch.STL" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="shoulder_pitch_collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/shoulder_pitch.STL" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>
<!-- ELBOW MACRO-->
<xacro:macro name="elbow_inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="elbow_visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/elbow_pitch.STL" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="orange"/>         
  </visual>
</xacro:macro>

<xacro:macro name="elbow_collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/elbow_pitch.STL" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>
<!-- WRIST PITCH MACRO-->
<xacro:macro name="wrist_pitch_inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="wrist_pitch_visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/wrist_pitch.STL" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="orange"/>         
  </visual>
</xacro:macro>

<xacro:macro name="wrist_pitch_collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/wrist_pitch.STL" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>
<!-- WRIST_YAW MACRO-->
<xacro:macro name="wrist_yaw_inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="wrist_yaw_visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/wrist_yaw.STL" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="orange"/>         
  </visual>
</xacro:macro>

<xacro:macro name="wrist_yaw_collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/wrist_yaw.STL" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>
<!-- WRIST_ROLL MACRO-->
<xacro:macro name="wrist_roll_inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="wrist_roll_visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/wrist_roll.STL" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="orange"/>         
  </visual>
</xacro:macro>

<xacro:macro name="wrist_roll_collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/wrist_roll.STL" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>


=============================================================================================================================================
<!-- LINKS -->

  <link name="bot">
    <!--<xacro:BotInertial trans="0 0 0" rpy="0 0 -1.57"/>-->  
    <xacro:BotVisual trans="0 0 0" rpy="0 0 -1.57"/>
    <xacro:BotCollision trans="0 0 0" rpy="0 0 -1.57"/>
  </link>
 
  <link name="shoulder_yaw_motor">
    <xacro:shoulder_yaw_inertial trans="0.13 -0.02 0.1715" rpy="0 0 0 "/>  
    <xacro:shoulder_yaw_visual trans="0.13 -0.02 0.1715" rpy="0 0 0 "/>
    <xacro:shoulder_yaw_collision trans="0.13 -0.02 0.1715" rpy="0 0 0"/>
  </link>

  <link name="shoulder_bracket">
    <xacro:shoulder_yaw_brak_inertial trans="-0.019 -0.062 0.0" rpy="0 0 0 "/>
    <xacro:shoulder_yaw_brak_visual trans="-0.019 -0.062 0" rpy="0 0 0 "/>
    <xacro:shoulder_yaw_brak_collision trans="-0.019 -0.062 0" rpy="0 0 0 "/>
  </link>  

  <link name="shoulder_pitch_motor">
    <xacro:shoulder_pitch_inertial trans="0.09 0 -0.00120" rpy="-1.57 3.14 1.57"/>  
    <xacro:shoulder_pitch_visual trans="0.09 0.06 -0.0120" rpy="-1.57 3.14 1.57"/>
    <xacro:shoulder_pitch_collision trans="0.09 0 -0.0120" rpy="-1.57 3.14 1.57"/>
  </link>

 
  <link name="elbow_motor">
    <xacro:elbow_inertial trans="0.0180 -0.09 -0.02" rpy="-1.57 3.14 0"/>  
    <xacro:elbow_visual trans="0.0180 -0.09 -0.02" rpy="-1.57 3.14 0"/>
    <xacro:elbow_collision trans="0.0180 -0.09 -0.02" rpy="-1.57 3.14 0"/>
  </link>
 


  <link name="wrist_pitch_motor">
    <xacro:wrist_pitch_inertial trans="0.0090 -0.05 -0.009" rpy="-1.57 0 1.57"/>
    <xacro:wrist_pitch_visual trans="0.0090 -0.05 -0.009" rpy="-1.57 3.14 0"/>
    <xacro:wrist_pitch_collision trans="0.0090 -0.05 -0.009" rpy="-1.57 0 1.57"/>
  </link>

  <link name="wrist_yaw_motor">
    <xacro:wrist_yaw_inertial trans="0.02 -0.055 -0.063" rpy="0 0 3.14"/>
    <xacro:wrist_yaw_visual trans="0.02 -0.055 -0.063" rpy="1.57 0 3.14"/>
    <xacro:wrist_yaw_collision trans="0.02 -0.055 -0.063" rpy="0 0 3.14"/>
  </link>
  
  <link name="wrist_roll_motor">
    <xacro:wrist_roll_inertial trans="-0.02 -0.06 -0.026" rpy="-1.57 3.14 0"/>
    <xacro:wrist_roll_visual trans="-0.02 -0.06 -0.026" rpy="-1.57 3.14 0"/>
    <xacro:wrist_roll_collision trans="-0.02 -0.06 -0.026" rpy="-1.57 3.14 0"/> 
  </link>

    
 <!-- JOINTS -->
  <xacro:FxdJoint id="bot_joint" trans="0 0 0" rpy="0 0 0" parent="bot" child="shoulder_yaw_motor"/>
  <xacro:Revjoint id="shoulder_yaw" trans="0.1765 -0.003 0.26" rpy="0 0 0" parent="shoulder_yaw_motor" child="shoulder_bracket" axis="0 0 1" l="-3.14" u="3.14" v="1.0"/>
  <xacro:Revjoint id="shoulder_pitch" trans="0 0.010 0.040" rpy="0 0 0.0" parent="shoulder_bracket" child="shoulder_pitch_motor" axis="0 1 0" l="-1.6592" u="1.727" v="1.0"/>
  <xacro:Revjoint id="elbow" trans="${0.052 + (length) - 0.150} 0 0.2" rpy="0 0 0" parent="shoulder_pitch_motor" child="elbow_motor" axis="0 1 0" l="-1.9262" u="1.934" v="1.0"/>
  <xacro:Revjoint id="wrist_pitch" trans="${length + 0.052 - 0.144} 0 0.196 " rpy="0 0 0" parent="elbow_motor" child="wrist_pitch_motor" axis="0 1 0" l="-2.29" u="0.718" v="1.0"/>
  <xacro:Revjoint id="wrist_yaw" trans="-0.080 0 0.05" rpy="0 0 0" parent="wrist_pitch_motor" child="wrist_yaw_motor" axis="0 0 1" l="-1.43" u="+2.11" v="1.0"/> 
  <xacro:Revjoint id="wrist_roll" trans="0 0 -0.0415" rpy="0 0 0" parent="wrist_yaw_motor" child="wrist_roll_motor" axis="1 0 0" l="-2.617" u="+2.617" v="1.0"/>  
  
</robot>
