<?xml version ="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_manipulator">

<material name="white">
  <color rgba="1 1 1 1"/>
</material>  

<xacro:property name="MXLength" value="0.0611"/>
<xacro:property name="MXWidth" value="0.041"/>
<xacro:property name="MXDepth" value="0.0402"/>

<xacro:property name="AXLength" value="0.05"/>
<xacro:property name="AXWidth" value="0.032"/>
<xacro:property name="AXDepth" value="0.04"/>

<xacro:property name="length" value="0.096"/>

<!-- MACROS -->

<xacro:macro name="MXInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="MXVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/dynamixel_x64series.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="MXCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.041 0.0402 0.0611"/>
      </geometry>    
    </collision> 
</xacro:macro>

<xacro:macro name="BotInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="BotVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/bot.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="BotCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/bot.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>

<xacro:macro name="MXCollision_dual_motor" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.041 0.0602 0.1480"/>
      </geometry>    
    </collision> 
</xacro:macro> 

<xacro:macro name="AXInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.05573" />
    <inertia ixx="0.00001611154" ixy="0.00000001397" ixz="0.0" iyy="0.00000888743" iyz="0.00000015948" izz="0.00001354172" />
  </inertial>
</xacro:macro>

<xacro:macro name="AXVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/AX-12_18A - dynamixel_AXseries-1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="AXCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.032 0.04 0.05"/>
      </geometry>    
    </collision> 
</xacro:macro>

<xacro:macro name="BracketInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.00712" />
    <inertia ixx="0.00000174511" iyy="0.00000379922" ixz="0.0" ixy="0.0" iyz="0.0" izz="0.00000357521" />
  </inertial>
</xacro:macro>

<xacro:macro name="BracketVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/FR05-H101K.stl" scale="0.001 0.001 0.001" />
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="BracketCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/FR05-H101K.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>  

<xacro:macro name="AxBracketInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.00712" />
    <inertia ixx="0.00000174511" iyy="0.00000379922" ixz="0.0" ixy="0.0" iyz="0.0" izz="0.00000357521" />
  </inertial>
</xacro:macro>

<xacro:macro name="AxBracketVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/F4.stl" scale="0.001 0.001 0.001" />
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="AxBracketCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/F4.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>  

<xacro:macro name="LinkInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="${0.005*length}" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394"/>
  </inertial>
</xacro:macro>

<xacro:macro name="LinkVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <box size="0.04 0.04 ${length}"/>
    </geometry>
    <material name="white"/>       
  </visual>
</xacro:macro>

<xacro:macro name="LinkCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.04 0.04 ${length}"/>
      </geometry>    
    </collision> 
</xacro:macro> 

<!-- Macros of the J plate -->

<xacro:macro name="roll_j_plate_Inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="roll_j_plate_Visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/gripper_Centering.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="roll_j_plate_Collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/gripper_Centering.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>

<!-- Macros of the gripper -->

<xacro:macro name="gripper_Inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="gripper_Visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/gripper.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="gripper_Collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/gripper.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>

<xacro:macro name="Revjoint" params="id trans rpy parent child axis l u v">
    <joint name="${id}" type="revolute">
      <origin xyz="${trans}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${axis}"/>
      <limit lower="${l}" upper="${u}" effort="30" velocity="${v}"/>
    </joint>
</xacro:macro> 

<xacro:macro name="FxdJoint" params="id parent child">
    <joint name="${id}" type="fixed">
      <parent link="${parent}"/>
      <child link="${child}"/>
    </joint>
</xacro:macro>    

<xacro:macro name="F10Inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.00712" />
    <inertia ixx="0.00000174511" iyy="0.00000379922" ixz="0.0" ixy="0.0" iyz="0.0" izz="0.00000357521" />
  </inertial>
</xacro:macro>

<xacro:macro name="F10Visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/F10.stl" scale="0.001 0.001 0.001" />
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="F10Collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/F10.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>  

<!-- LINKS -->

  <link name="bot">
    <xacro:BotInertial trans="0 0 0" rpy="0 0 0 "/>  
    <xacro:BotVisual trans="0 0 0" rpy="0 0 0 "/>
    <xacro:BotCollision trans="0 0 0" rpy="0 0 0"/>
  </link>
 
  <link name="shoulder_yaw_motor">
    <xacro:MXInertial trans="0 0 0" rpy="0 0 0 "/>  
    <xacro:MXVisual trans="0 0.188 0.2349" rpy="0 0 0 "/>
    <xacro:MXCollision trans="0 0.188 0.2349" rpy="0 0 0"/>
  </link>

  <link name="shoulder_bracket">
    <xacro:BracketInertial trans="0 0 0.025" rpy="0 3.14 0 "/>
    <xacro:BracketVisual trans="0 0 0" rpy="0 3.14 0 "/>
    <xacro:BracketCollision trans="0 0 0" rpy="0 3.14 0 "/>
  </link>  

  <link name="shoulder_pitch_motor">
    <xacro:MXInertial trans="0 0 0" rpy="1.57 -3.14 1.57"/>  
    <xacro:MXVisual trans="0 0 0" rpy="1.57 -3.14 1.57"/>
    <xacro:MXCollision_dual_motor trans="0 0 0" rpy="1.57 -3.14 1.57"/>
  </link>

  <link name="biscep">
    <xacro:LinkInertial trans="0 0 ${0.051+(length/2)}" rpy="0 0 0" />
    <xacro:LinkVisual trans="0 0 ${0.051+(length/2)}" rpy="0 0 0" />
    <xacro:LinkCollision trans="0 0 ${0.051+(length/2)}" rpy="0 0 0" />
  </link> 

  <link name="elbow_bracket">
    <xacro:BracketInertial trans="0 0 ${0.052+length}" rpy="0 3.14 0"/>
    <xacro:BracketVisual trans="0 0 ${0.052+length}" rpy="0 3.14 0"/>
    <xacro:BracketCollision trans="0 0 ${0.052+length}" rpy="0 3.14 0"/>
  </link>   

  <link name="elbow_motor">
    <xacro:MXInertial trans="0 0 0" rpy="1.57 0 0"/>  
    <xacro:MXVisual trans="0 0 0" rpy="1.57 3.14 -1.57"/>
    <xacro:MXCollision trans="0 0 0" rpy="1.57 3.14 -1.57"/>
  </link>

  <link name="forearm">
    <xacro:LinkInertial trans="0 0 ${0.052+(length/2)}" rpy="0 0 0" />
    <xacro:LinkVisual trans="0 0 ${0.052+(length/2)}" rpy="0 0 0" />
    <xacro:LinkCollision trans="0 0 ${0.052+(length/2)}" rpy="0 0 0" />
  </link> 
  
  <link name="wrist_bracket">
    <xacro:AxBracketInertial trans="0 0 ${0.052+length+0.054}" rpy="1.57 0 1.57"/>
    <xacro:AxBracketVisual trans="0 0 ${0.052+length+0.054}" rpy="1.57 0 1.57"/>
    <xacro:AxBracketCollision trans="0 0 ${0.052+length+0.054}" rpy="1.57 0 1.57"/>
  </link>

  <link name="wrist_pitch_motor">
    <xacro:AXInertial trans="0 0 0" rpy="-1.57 0 -1.57"/>
    <xacro:AXVisual trans="0 0 0" rpy="-1.57 0 -1.57"/>
    <xacro:AXCollision trans="0 0 0" rpy="-1.57 0 -1.57"/>
  </link>     

  <link name="wrist_roll_motor">
    <xacro:AXInertial trans="0 0 0.078" rpy="-1.57 3.14 0"/>
    <xacro:AXVisual trans="0 0 0.078" rpy="-1.57 3.14 0"/>
    <xacro:AXCollision trans="0 0 0.078" rpy="-1.57 3.14 0"/>
  </link>


  <link name="roll_j_plate">
    <xacro:roll_j_plate_Inertial trans="0 0 0" rpy="0 0 0"/>
    <xacro:roll_j_plate_Visual trans="-0.025 0 -0.052" rpy="-1.57 -1.57 0"/>
    <xacro:roll_j_plate_Collision trans="-0.025 0 -0.052" rpy="-1.57 -1.57 0"/>
  </link>

 <link name="gripper">
    <xacro:gripper_Inertial trans="0 0 0" rpy="0 0 0"/>
    <xacro:gripper_Visual trans="0.008 0.07 -0.009" rpy="0 3.14 0"/>
    <xacro:gripper_Collision trans="0.008 0.07 -0.009" rpy="0 3.14 0"/>
  </link>
  
    
 <!-- JOINTS -->
  <xacro:FxdJoint id="bot_joint" parent="bot" child="shoulder_yaw_motor"/>
  <xacro:Revjoint id="shoulder_yaw" trans="0 0.188 0.2577" rpy="0 0 3.14" parent="shoulder_yaw_motor" child="shoulder_bracket" axis="0 0 1" l="-3.0357" u="3.24426" v="1.0"/>
  <!-- 0 0 0.025 -->
  <xacro:Revjoint id="shoulder_pitch" trans="0 0 0.035" rpy="0 0 0" parent="shoulder_bracket" child="shoulder_pitch_motor" axis="1 0 0" l="-1.973232422" u="1.916503906" v="1.0"/>
  <xacro:FxdJoint id="s1_l2" parent="shoulder_pitch_motor" child="biscep"/>
  <xacro:FxdJoint id="l2_l2B" parent="biscep" child="elbow_bracket"/>
  <xacro:Revjoint id="elbow" trans="0 0 ${0.052 + (length) + 0.038}" rpy="0 0 0" parent="elbow_bracket" child="elbow_motor" axis="1 0 0" l="-1.99" u="1.971699219" v="1.0"/>
  <xacro:FxdJoint id="e_l3" parent="elbow_motor" child="forearm"/>
  <xacro:FxdJoint id="l3_l3B" parent="forearm" child="wrist_bracket"/>
  <xacro:Revjoint id="wrist_pitch" trans="0 0 ${length + 0.052 + 0.054}" rpy="0 0 0" parent="wrist_bracket" child="wrist_pitch_motor" axis="1 0 0" l="-2.36344086" u="2.368556533" v="1.0"/>
  <xacro:FxdJoint id="WP_WR" parent="wrist_pitch_motor" child="wrist_roll_motor" />
  <xacro:Revjoint id="wrist_roll" trans="0 0.02 0.082" rpy="0 3.14 0" parent="wrist_roll_motor" child="roll_j_plate" axis="0 1 0" l="-2" u="+2" v="1.0"/>
  <xacro:FxdJoint id="roll_plate_gripper" parent="roll_j_plate" child="gripper" /> 
  
</robot>